In [1]:
import pandas as pd
from Bio import SeqIO

# TODO:
1. Сдлеать рисунки для по geo3918, geo3817
2. Сделать колинеарный анализ на основании сравнения геномов гео в seed
3. Сделать подобное сравненеи и для Jay 535

## Создание файлов для CIRCOS geo3918

**karyotype** -- содержит иформацию о хромосомах или контигах имеет следующее строение:

chr - ID LABEL START END COLOR

In [3]:
#Для этого можно прочитать файл с контигами и записать все необходимые данные из него.
for num, seq in enumerate(SeqIO.parse(open('/home/aster/Project_Geoarchaeota_28.11/data/sequences_annotation/1448933.3.contigs.fa'), 'fasta'), start=1):
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918/data/karyotype_geo3918.txt', 'a') as write_file:
        write_file.write(f"chr - {seq.name.split('_')[0]} cn_{num} 0 {len(seq)} green")

FileNotFoundError: [Errno 2] No such file or directory: '/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/data/karyotype.txt'

**high light** -- Используется для создания секторов разных цевтов, например для подсветки определенных генов

Хорошо сочитается если с COG нотацией генов

Файл имеет следующую структуру:

ID START END COLOR

In [4]:
gff_geo3918 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/data/sequences_annotation/1448933.3.gff', sep='\t', header=None)
gff_geo3918_plus_strand = gff_geo3918[gff_geo3918[6] == '+']
gff_geo3918_minus_strand = gff_geo3918[gff_geo3918[6] == '-']

In [13]:
for idx, row in gff_geo3918_plus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/data/highlight_plus_strand.txt', 'a') as write_file:
        write_file.write(f"contig {row[3]} {row[4]} fill_color=red\n")

In [14]:
for idx, row in gff_geo3918_minus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/data/highlight_minus_strand.txt', 'a') as write_file:
        write_file.write(f"contig {row[3]} {row[4]} fill_color=blue\n")

### Тоже самое но с COG

In [42]:
gff_geo3918 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/gff_files/geo_3918.gff', sep='\t', header=None)
eggNOG_annot = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/eggNog_mapper/MM_k15bh4a0.emapper.annotations(1).tsv', sep='\t')

In [43]:
gff_geo3918.head(2)

,0,1,2,3,4,5,6,7,8
0,contig_1_pilon_pilon_pilon,FIG,CDS,2,2227,.,-,2,ID=fig|1448933.3.peg.1;Name=beta-glucosidase (...
1,contig_1_pilon_pilon_pilon,FIG,CDS,2259,3155,.,-,0,ID=fig|1448933.3.peg.2;Name=hypothetical protein

In [44]:
eggNOG_annot.head(2)

,ID,seed_ortholog,evalue,score,eggNOG_OGs,max_annot_lvl,COG_category,Description,Preferred_name,GOs,...,KEGG_ko,KEGG_Pathway,KEGG_Module,KEGG_Reaction,KEGG_rclass,BRITE,KEGG_TC,CAZy,BiGG_Reaction,PFAMs
0,fig|1448933.3.peg.1,930945.SiRe_2208,8.040000e-276,784.0,"COG1472@1|root,arCOG04634@2157|Archaea,2XPMS@2...",28889|Crenarchaeota,G,Fibronectin type III-like domain,-,-,...,ko:K05349,"ko00460,ko00500,ko00940,ko01100,ko01110,map004...",-,"R00026,R02558,R02887,R02985,R03527,R04949,R049...","RC00049,RC00059,RC00171,RC00262,RC00397,RC0045...","ko00000,ko00001,ko01000",-,GH3,-,"Fn3-like,Glyco_hydro_3,Glyco_hydro_3_C"
1,fig|1448933.3.peg.5,1459636.NTE_01989,2.680000e-26,104.0,"COG1832@1|root,arCOG04227@2157|Archaea,41SMT@6...",651137|Thaumarchaeota,S,CoA binding domain,-,-,...,ko:K06929,-,-,-,-,ko00000,-,-,-,CoA_binding_2

In [7]:
#color dict
d = {'J':'ff0000', 'A':'c2af58', 'K':'ff9900', 'L':'ffff00', 'B':'ffc600',
    'D':'99ff00', 'Y':'493126', 'V':'ff008a', 'T':'0000ff', 'M':'9ec928',
    'N':'006633', 'Z':'660099', 'W':'336699', 'U':'33cc99', 'O':'00ffff', 
    'C':'9900ff', 'G':'805642', 'E':'99334d', 'H':'727dcc', 'I':'5c5a1b',
    'P':'0099ff', 'Q':'ffcc99', 'R':'ff9999','S':'d6aadf', 'F':'99334d',
    'IQ':'ffcc99',
    '-':'white',
    'EGP':'b8b100',
    'CP':'9900ff',
    'JM':'ff0000',
    'EP':'99334d',
    'NU':'006633',
    'HP':'727dcc',
    'GM':'805642',
    ################
    'LT':'ffff00',
    'KL':'ff9900',
    'BQ':'ffc600',
    'EH':'99334d',
    'FG':'99334d',
    'OU':'00ffff',
    'CE':'9900ff'
    }

In [46]:
for idx, row in gff_geo3918.iterrows():
    for idx2, row2, in eggNOG_annot.iterrows():
        if row2['ID'] in row[8]:
            gff_geo3918.loc[idx, 'color'] = f"fill_color={d[row2['COG_category']]}"

In [47]:
gff_geo3918

,0,1,2,3,4,5,6,7,8,color
0,contig_1_pilon_pilon_pilon,FIG,CDS,2,2227,.,-,2,ID=fig|1448933.3.peg.1;Name=beta-glucosidase (...,fill_color=805642
1,contig_1_pilon_pilon_pilon,FIG,CDS,2259,3155,.,-,0,ID=fig|1448933.3.peg.2;Name=hypothetical protein,NaN
2,contig_1_pilon_pilon_pilon,FIG,CDS,3265,4527,.,-,1,ID=fig|1448933.3.peg.3;Name=hypothetical protein,NaN
3,contig_1_pilon_pilon_pilon,FIG,CDS,4530,4667,.,-,0,ID=fig|1448933.3.peg.4;Name=hypothetical protein,NaN
4,contig_1_pilon_pilon_pilon,FIG,CDS,4690,5208,.,+,1,ID=fig|1448933.3.peg.5;Name=hypothetical protein,fill_color=d6aadf
...,...,...,...,...,...,...,...,...,...,...
1550,contig_1_pilon_pilon_pilon,FIG,tRNA,1124017,1124091,.,-,.,ID=fig|1448933.3.rna.43;Name=tRNA-Gly-TCC,NaN
1551,contig_1_pilon_pilon_pilon,FIG,tRNA,1124017,1124091,.,-,.,ID=fig|1448933.3.rna.43;Name=tRNA-Gly-TCC,NaN
1552,contig_1_pilon_pilon_pilon,FIG,tRNA,1169723,1169797,.,+,.,ID=fig|1448933.3.rna.44;Name=tRNA-Thr-TGT,NaN
1553,contig_1_pilon_pilon_pilon,FIG,tRNA,1169723,1169797,.,+,.,ID=fig|1448933.3.rna.44;Name=tRNA-Thr-TGT,NaN
1554,contig_1_pilon_pilon_pilon,FIG,tRNA,1169723,1169797,.,+,.,ID=fig|1448933.3.rna.44;Name=tRNA-Thr-TGT,NaN

In [64]:
rna_cas = gff_geo3918[(gff_geo3918[8].str.contains('Cass'))|(gff_geo3918[8].str.contains('Name=tRNA-'))|(gff_geo3918[8].str.contains('rRNA_'))]

In [84]:
for idx, row in rna_cas.iterrows():
    if 'Name=tRNA-' in row[8]:
        rna_cas.loc[idx, 'color'] = 'fill_color=vvdblue'
for idx, row in rna_cas.iterrows():
    if 'Cass' in row[8]:
        rna_cas.loc[idx, 'color'] = 'fill_color=vdred'
for idx, row in rna_cas.iterrows():
    if 'rRNA_' in row[8]:
        rna_cas.loc[idx, 'color'] = 'fill_color=vvdgreen'

In [73]:
gff_geo3918[8].isin(rna_cas[8])

0       False
1       False
2       False
3       False
4       False
        ...
1550     True
1551     True
1552     True
1553     True
1554     True
Name: 8, Length: 1555, dtype: bool

In [74]:
gff_geo3918 =gff_geo3918[~gff_geo3918[8].isin(rna_cas[8])]

In [76]:

gff_geo3918_plus_strand = gff_geo3918[gff_geo3918[6] == '+']
gff_geo3918_minus_strand = gff_geo3918[gff_geo3918[6] == '-']

In [77]:
gff_geo3918_plus_strand

,0,1,2,3,4,5,6,7,8,color
4,contig_1_pilon_pilon_pilon,FIG,CDS,4690,5208,.,+,1,ID=fig|1448933.3.peg.5;Name=hypothetical protein,fill_color=d6aadf
15,contig_1_pilon_pilon_pilon,FIG,CDS,15761,15955,.,+,2,ID=fig|1448933.3.peg.16;Name=hypothetical protein,fill_color=805642
16,contig_1_pilon_pilon_pilon,FIG,CDS,15989,17098,.,+,2,ID=fig|1448933.3.peg.17;Name=N-acyl-L-amino ac...,fill_color=99334d
19,contig_1_pilon_pilon_pilon,FIG,CDS,19106,19795,.,+,2,ID=fig|1448933.3.peg.20;Name=Sugar fermentatio...,fill_color=d6aadf
20,contig_1_pilon_pilon_pilon,FIG,CDS,19792,20514,.,+,1,ID=fig|1448933.3.peg.21;Name=Oxidoreductase%2C...,fill_color=5c5a1b
...,...,...,...,...,...,...,...,...,...,...
1408,contig_1_pilon_pilon_pilon,FIG,CDS,1410616,1411353,.,+,1,ID=fig|1448933.3.peg.1409;Name=hypothetical pr...,fill_color=5c5a1b
1410,contig_1_pilon_pilon_pilon,FIG,CDS,1413740,1414174,.,+,2,ID=fig|1448933.3.peg.1411;Name=hypothetical pr...,fill_color=805642
1417,contig_1_pilon_pilon_pilon,FIG,CDS,1421814,1423343,.,+,0,ID=fig|1448933.3.peg.1418;Name=hypothetical pr...,fill_color=d6aadf
1418,contig_1_pilon_pilon_pilon,FIG,CDS,1423380,1424819,.,+,0,ID=fig|1448933.3.peg.1419;Name=hypothetical pr...,fill_color=805642
1422,contig_1_pilon_pilon_pilon,FIG,CDS,1427650,1429827,.,+,1,ID=fig|1448933.3.peg.1423;Name=alpha-xylosidas...,fill_color=805642

In [78]:
for idx, row in gff_geo3918_plus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918/data/highlight_plus_strand.txt', 'a') as write_file:
        write_file.write(f"contig {row[3]} {row[4]} {row['color']}\n")

In [79]:
for idx, row in gff_geo3918_minus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918/data/highlight_minus_strand.txt', 'a') as write_file:
        write_file.write(f"contig {row[3]} {row[4]} {row['color']}\n")

In [87]:
for idx, row in rna_cas.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918/data/rna_cas_3_ring.txt', 'a') as write_file:
        write_file.write(f"contig {row[3]} {row[4]} {row['color']}\n")

### CG_skew

In [3]:
def CG_cont(lis:str) -> float:
    lis = lis.upper()
    GC = lis.count('G') + lis.count('C')
    return GC/len(lis)

def CG_skew(lis:str) -> float:
    lis = lis.upper()
    G = lis.count('G')
    C = lis.count('C')
    return (G - C)/(G + C)

In [5]:
def slider(seq,sliding_window, step_size):
    #sliding_window = 1000
    step = 0
    #step_size = 1000
    r_bords = []
    GCskew = []
    #GCcont = []
    l_bords = []
    for i in range(0,len(seq)):

        l_bord = step
        r_bord = sliding_window + l_bord
        step += step_size
        window = seq[l_bord:r_bord]

        l_bords.append(l_bord+1)
        r_bords.append(r_bord-sliding_window+1)
        GCskew.append(CG_skew(window))
        #GCcont.append(CG_cont(window))

        if r_bord >= len(seq):
            break

    GCskew.append((GCskew[0] + GCskew[-1])/2) #Замыкание кольца гистограммы
    #GCcont.append((GCcont[0] + GCcont[-1])/2)
    l_bords.append(l_bords[-1] + sliding_window-step_size )
    r_bords.append(r_bords[-1]  + sliding_window )
    return list(zip(l_bords,r_bords,GCskew))

In [83]:
for sequence in SeqIO.parse(open('/home/aster/Project_Geoarchaeota_28.11/data/sequences_annotation/1448933.3.contigs.fa','r'), 'fasta'):
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918/data/geo3918_GC_skew.txt','a') as skew_file:

        if len(sequence.seq) >= 5000:
            lst = slider(str(sequence.seq), sliding_window=5000,step_size=1000)
            for i,j,k in lst:
                if k > 0:
                    skew_file.write(f"{sequence.name.split('_')[0]} {i} {j} {k} fill_color=green\n")
                else:
                    skew_file.write(f"{sequence.name.split('_')[0]} {i} {j} {k} fill_color=red\n")

        else:
            lst = slider(str(sequence.seq), sliding_window=1000,step_size=1000)
            for i,j,k in lst:
                if k > 0:
                    skew_file.write(f"{sequence.name.split('_')[0]} {i} {j} {k} fill_color=green\n")
                else:
                    skew_file.write(f"{sequence.name.split('_')[0]} {i} {j} {k} fill_color=red\n")

## Создание того же но для geo3817

In [2]:
for num, seq in enumerate(SeqIO.parse(open('/home/aster/Project_Geoarchaeota_28.11/3817-70/data/sequence_annotation/1448933.6.contigs.fa'), 'fasta'), start=1):
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3817/data/geo3817_karyotype.txt', 'a') as write_file:
        write_file.write(f"chr - {seq.name} contig_{num} 0 {len(seq)} blue\n")

In [3]:
gff_geo3817 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/gff_files/geo_3817.gff', sep='\t', header=None)

In [4]:
eggNOG_annot = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/eggNOG_annot/geo3817_eggNOG.tsv', sep='\t', header=4)

In [5]:
rna_cas = gff_geo3817[(gff_geo3817[8].str.contains('Cass'))|(gff_geo3817[8].str.contains('Name=tRNA-'))|(gff_geo3817[8].str.contains('rRNA_'))]

In [8]:
for idx, row in gff_geo3817.iterrows():
    for idx2, row2, in eggNOG_annot.iterrows():
        if row2['Name'] in row[8]:
            gff_geo3817.loc[idx, 'color'] = f"fill_color={d[row2['COG_category']]}"

In [9]:
gff_geo3817

,0,1,2,3,4,5,6,7,8,color
0,NODE_10_length_11968_cov_535.958785,FIG,CDS,2,208,.,+,2,ID=fig|1448933.6.peg.1;Name=hypothetical protein,NaN
1,NODE_10_length_11968_cov_535.958785,FIG,CDS,266,2443,.,-,2,ID=fig|1448933.6.peg.2;Name=alpha-xylosidase (...,fill_color=805642
2,NODE_10_length_11968_cov_535.958785,FIG,CDS,2465,2680,.,-,2,ID=fig|1448933.6.peg.3;Name=hypothetical protein,NaN
3,NODE_10_length_11968_cov_535.958785,FIG,CDS,2729,3592,.,+,2,ID=fig|1448933.6.peg.4;Name=hypothetical protein,NaN
4,NODE_10_length_11968_cov_535.958785,FIG,CDS,3615,4316,.,+,0,ID=fig|1448933.6.peg.5;Name=7-cyano-7-deazagua...,fill_color=727dcc
...,...,...,...,...,...,...,...,...,...,...
1627,NODE_8_length_17721_cov_583.980471,FIG,tRNA,10958,11042,.,-,.,ID=fig|1448933.6.rna.42;Name=tRNA-Ser-CGA,NaN
1628,NODE_8_length_17721_cov_583.980471,FIG,tRNA,10958,11042,.,-,.,ID=fig|1448933.6.rna.42;Name=tRNA-Ser-CGA,NaN
1629,NODE_8_length_17721_cov_583.980471,FIG,tRNA,16531,16630,.,+,.,ID=fig|1448933.6.rna.43;Name=tRNA-Ser-GGA,NaN
1630,NODE_8_length_17721_cov_583.980471,FIG,tRNA,16531,16630,.,+,.,ID=fig|1448933.6.rna.43;Name=tRNA-Ser-GGA,NaN
1631,NODE_8_length_17721_cov_583.980471,FIG,tRNA,16531,16630,.,+,.,ID=fig|1448933.6.rna.43;Name=tRNA-Ser-GGA,NaN

In [13]:
for idx, row in rna_cas.iterrows():
    if 'Name=tRNA-' in row[8]:
        rna_cas.loc[idx, 'color'] = 'fill_color=vvdblue'
for idx, row in rna_cas.iterrows():
    if 'Cass' in row[8]:
        rna_cas.loc[idx, 'color'] = 'fill_color=vdred'
for idx, row in rna_cas.iterrows():
    if 'rRNA_' in row[8]:
        rna_cas.loc[idx, 'color'] = 'fill_color=vvdgreen'

/tmp/ipykernel_69016/1153070891.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rna_cas.loc[idx, 'color'] = 'fill_color=vvdblue'

In [14]:
gff_geo3817 = gff_geo3817[~gff_geo3817[8].isin(rna_cas[8])]

In [15]:
gff_geo3817_plus_strand = gff_geo3817[gff_geo3817[6] == '+']
gff_geo3817_minus_strand = gff_geo3817[gff_geo3817[6] == '-']

In [29]:
for idx, row in gff_geo3817_plus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3817/data/highlight_plus_strand.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

In [30]:
for idx, row in gff_geo3817_minus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3817/data/highlight_minus_strand.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

In [31]:
for idx, row in rna_cas.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3817/data/rna_cas_3_ring.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

In [32]:
for sequence in SeqIO.parse(open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/fna_files/geo3817_contigs.fa','r'), 'fasta'):
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3817/data/geo3918_GC_skew.txt','a') as skew_file:

        if len(sequence.seq) >= 5000:
            lst = slider(str(sequence.seq), sliding_window=5000,step_size=1000)
            for i,j,k in lst:
                if k > 0:
                    skew_file.write(f"{sequence.name} {i} {j} {k} fill_color=green\n")
                else:
                    skew_file.write(f"{sequence.name} {i} {j} {k} fill_color=red\n")

        else:
            lst = slider(str(sequence.seq), sliding_window=1000,step_size=1000)
            for i,j,k in lst:
                if k > 0:
                    skew_file.write(f"{sequence.name} {i} {j} {k} fill_color=green\n")
                else:
                    skew_file.write(f"{sequence.name} {i} {j} {k} fill_color=red\n")

## geo both

In [1]:
import pandas as pd
from Bio import SeqIO

In [2]:
for num, seq in enumerate(SeqIO.parse(open('/home/aster/Project_Geoarchaeota_28.11/data/sequences_annotation/1448933.3.contigs.fa'), 'fasta'), start=1):
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918_geo3817/data/karyotype_both.txt', 'a') as write_file:
        write_file.write(f"chr - {seq.name} cn_{num} 0 {len(seq)} green\n")
        
for num, seq in enumerate(SeqIO.parse(open('/home/aster/Project_Geoarchaeota_28.11/3817-70/data/sequence_annotation/1448933.6.contigs.fa'), 'fasta'), start=1):
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918_geo3817/data/karyotype_both.txt', 'a') as write_file:
        write_file.write(f"chr - {seq.name} contig_{num} 0 {len(seq)} blue\n")

In [3]:
d = {'J':'ff0000', 'A':'c2af58', 'K':'ff9900', 'L':'ffff00', 'B':'ffc600',
    'D':'99ff00', 'Y':'493126', 'V':'ff008a', 'T':'0000ff', 'M':'9ec928',
    'N':'006633', 'Z':'660099', 'W':'336699', 'U':'33cc99', 'O':'00ffff', 
    'C':'9900ff', 'G':'805642', 'E':'99334d', 'H':'727dcc', 'I':'5c5a1b',
    'P':'0099ff', 'Q':'ffcc99', 'R':'ff9999','S':'d6aadf', 'F':'99334d',
    'IQ':'ffcc99',
    '-':'white',
    'EGP':'b8b100',
    'CP':'9900ff',
    'JM':'ff0000',
    'EP':'99334d',
    'NU':'006633',
    'HP':'727dcc',
    'GM':'805642',
    ################
    'LT':'ffff00',
    'KL':'ff9900',
    'BQ':'ffc600',
    'EH':'99334d',
    'FG':'99334d',
    'OU':'00ffff',
    'CE':'9900ff'
    }

In [97]:
gff_geo3918 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/data/sequences_annotation/1448933.3.gff', sep='\t', header=None)
eggNOG_annot_geo3918 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/eggNog_mapper/MM_k15bh4a0.emapper.annotations(1).tsv', sep='\t')
gff_geo3817 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/3817-70/data/sequence_annotation/1448933.6.gff', sep='\t', header=None)
eggNOG_annot_geo3817 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/3817-70/results/eggNOG5/MM_69m96w52.emapper.annotations.tsv', sep='\t', header=4)

In [98]:
for idx, row in gff_geo3918.iterrows():
    for idx2, row2, in eggNOG_annot_geo3918.iterrows():
        if row2['ID'] in row[8]:
            gff_geo3918.loc[idx, 'color'] = d[row2['COG_category']]

for idx, row in gff_geo3817.iterrows():
    for idx2, row2, in eggNOG_annot_geo3817.iterrows():
        if row2['Name'] in row[8]:
            gff_geo3817.loc[idx, 'color'] = d[row2['COG_category']]

In [99]:
gff_geo3918_plus_strand = gff_geo3918[gff_geo3918[6] == '+']
gff_geo3918_minus_strand = gff_geo3918[gff_geo3918[6] == '-']
gff_geo3817_plus_strand = gff_geo3817[gff_geo3817[6] == '+']
gff_geo3817_minus_strand = gff_geo3817[gff_geo3817[6] == '-']

In [13]:
for idx, row in gff_geo3918_plus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918_geo3817/data/highlight_plus_strand.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

for idx, row in gff_geo3918_minus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918_geo3817/data/highlight_minus_strand.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

for idx, row in gff_geo3817_plus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918_geo3817/data/highlight_plus_strand.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

for idx, row in gff_geo3817_minus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918_geo3817/data/highlight_minus_strand.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

### Coliniary

In [91]:
seed_compare = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/SEED/geo2geo_compare/Geo3918_toGeo3817_seq_compar.tsv', sep='\t')

In [102]:
seed_compare_parsed = seed_compare[['Gene id', 'Gene id.1']]
seed_compare_parsed = seed_compare_parsed[seed_compare_parsed['Gene id.1'] != ' ']
gff_geo3918['color'] = gff_geo3918['color'].fillna('gray_a2')

In [105]:
gff_geo3918

,0,1,2,3,4,5,6,7,8,color
0,contig_1_pilon_pilon_pilon,FIG,CDS,2,2227,.,-,2,ID=fig|1448933.3.peg.1;Name=beta-glucosidase (...,805642
1,contig_1_pilon_pilon_pilon,FIG,CDS,2259,3155,.,-,0,ID=fig|1448933.3.peg.2;Name=hypothetical protein,gray_a2
2,contig_1_pilon_pilon_pilon,FIG,CDS,3265,4527,.,-,1,ID=fig|1448933.3.peg.3;Name=hypothetical protein,gray_a2
3,contig_1_pilon_pilon_pilon,FIG,CDS,4530,4667,.,-,0,ID=fig|1448933.3.peg.4;Name=hypothetical protein,gray_a2
4,contig_1_pilon_pilon_pilon,FIG,CDS,4690,5208,.,+,1,ID=fig|1448933.3.peg.5;Name=hypothetical protein,d6aadf
...,...,...,...,...,...,...,...,...,...,...
1550,contig_1_pilon_pilon_pilon,FIG,tRNA,1124017,1124091,.,-,.,ID=fig|1448933.3.rna.43;Name=tRNA-Gly-TCC,gray_a2
1551,contig_1_pilon_pilon_pilon,FIG,tRNA,1124017,1124091,.,-,.,ID=fig|1448933.3.rna.43;Name=tRNA-Gly-TCC,gray_a2
1552,contig_1_pilon_pilon_pilon,FIG,tRNA,1169723,1169797,.,+,.,ID=fig|1448933.3.rna.44;Name=tRNA-Thr-TGT,gray_a2
1553,contig_1_pilon_pilon_pilon,FIG,tRNA,1169723,1169797,.,+,.,ID=fig|1448933.3.rna.44;Name=tRNA-Thr-TGT,gray_a2
1554,contig_1_pilon_pilon_pilon,FIG,tRNA,1169723,1169797,.,+,.,ID=fig|1448933.3.rna.44;Name=tRNA-Thr-TGT,gray_a2

In [107]:
for idx, row in seed_compare_parsed.iterrows():
    for idx2, row2 in gff_geo3918.iterrows():
        if row['Gene id'] in row2[8]:
            seed_compare_parsed.loc[idx,'start1'] = row2[3]
            seed_compare_parsed.loc[idx,'stop1'] = row2[4]
            seed_compare_parsed.loc[idx,'link_id_1'] = row2[0]
            seed_compare_parsed.loc[idx,'color'] = row2['color']

for idx, row in seed_compare_parsed.iterrows():
    for idx2, row2 in gff_geo3817.iterrows():
        if row['Gene id.1'] in row2[8]:
            seed_compare_parsed.loc[idx,'start2'] = row2[3]
            seed_compare_parsed.loc[idx,'stop2'] = row2[4]
            seed_compare_parsed.loc[idx,'link_id_2'] = row2[0]

In [108]:
seed_compare_parsed

,Gene id,Gene id.1,start1,stop1,link_id_1,color,start2,stop2,link_id_2
0,fig|1448933.3.peg.1,fig|1448933.6.peg.627,1427650.0,1429827.0,contig_1_pilon_pilon_pilon,805642,603733.0,605979.0,NODE_1_length_696707_cov_578.980505
1,fig|1448933.3.peg.2,fig|1448933.6.peg.626,311988.0,312881.0,contig_1_pilon_pilon_pilon,ff0000,602805.0,603701.0,NODE_1_length_696707_cov_578.980505
2,fig|1448933.3.peg.3,fig|1448933.6.peg.625,402182.0,402880.0,contig_1_pilon_pilon_pilon,d6aadf,601330.0,602553.0,NODE_1_length_696707_cov_578.980505
4,fig|1448933.3.peg.5,fig|1448933.6.peg.624,584564.0,584941.0,contig_1_pilon_pilon_pilon,9900ff,600737.0,601276.0,NODE_1_length_696707_cov_578.980505
5,fig|1448933.3.peg.6,fig|1448933.6.peg.623,686210.0,687178.0,contig_1_pilon_pilon_pilon,white,599843.0,600688.0,NODE_1_length_696707_cov_578.980505
...,...,...,...,...,...,...,...,...,...
1418,fig|1448933.3.peg.1419,fig|1448933.6.peg.8,1423380.0,1424819.0,contig_1_pilon_pilon_pilon,805642,181850.0,182095.0,NODE_2_length_425441_cov_628.256478
1419,fig|1448933.3.peg.1420,fig|1448933.6.peg.6,1425086.0,1425847.0,contig_1_pilon_pilon_pilon,805642,687629.0,688402.0,NODE_1_length_696707_cov_578.980505
1420,fig|1448933.3.peg.1421,fig|1448933.6.peg.5,1425844.0,1426545.0,contig_1_pilon_pilon_pilon,727dcc,574697.0,575809.0,NODE_1_length_696707_cov_578.980505
1421,fig|1448933.3.peg.1422,fig|1448933.6.peg.4,1426568.0,1427266.0,contig_1_pilon_pilon_pilon,d6aadf,478568.0,479374.0,NODE_1_length_696707_cov_578.980505
1422,fig|1448933.3.peg.1423,fig|1448933.6.peg.2,1427650.0,1429827.0,contig_1_pilon_pilon_pilon,805642,258917.0,260410.0,NODE_1_length_696707_cov_578.980505

In [109]:
for idx, row in seed_compare_parsed.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918_geo3817/data/links.txt', 'a') as link_file:
        link_file.write(f"rep{idx} {row['link_id_1']} {int(row['start1'])} {int(row['stop1'])}\nrep{idx} {row['link_id_2']} {int(row['start2'])} {int(row['stop2'])}\n")

In [110]:
for idx, row in seed_compare_parsed.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918_geo3817/data/links.txt', 'a') as link_file:
        link_file.write(f"{row['link_id_1']} {int(row['start1'])} {int(row['stop1'])} {row['link_id_2']} {int(row['start2'])} {int(row['stop2'])} color={row['color']}\n")

### Связи но с Jay 535 и Geo3918

Еще сделать цветак как в COG

In [1]:
import pandas as pd
from Bio import SeqIO

In [5]:
for num, seq in enumerate(SeqIO.parse(open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/fna_files/Jay_535_contigs.fa'), 'fasta'), start=1):
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/Jay_535_geo3918/data/karyotype_both.txt', 'a') as write_file:
        write_file.write(f"chr - {seq.name} cn_{num} 0 {len(seq)} blue\n")
        
for num, seq in enumerate(SeqIO.parse(open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/fna_files/geo3918_contigs.fa'), 'fasta'), start=1):
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/Jay_535_geo3918/data/karyotype_both.txt', 'a') as write_file:
        write_file.write(f"chr - {seq.name} contig_{num} 0 {len(seq)} green\n")

In [43]:
d = {'J':'ff0000', 'A':'c2af58', 'K':'ff9900', 'L':'ffff00', 'B':'ffc600',
    'D':'99ff00', 'Y':'493126', 'V':'ff008a', 'T':'0000ff', 'M':'9ec928',
    'N':'006633', 'Z':'660099', 'W':'336699', 'U':'33cc99', 'O':'00ffff', 
    'C':'9900ff', 'G':'805642', 'E':'99334d', 'H':'727dcc', 'I':'5c5a1b',
    'P':'0099ff', 'Q':'ffcc99', 'R':'ff9999','S':'d6aadf', 'F':'99334d',
    'IQ':'ffcc99',
    '-':'white',
    'EGP':'b8b100',
    'CP':'9900ff',
    'JM':'ff0000',
    'EP':'99334d',
    'NU':'006633',
    'HP':'727dcc',
    'GM':'805642',
    ################
    'LT':'ffff00',
    'KL':'ff9900',
    'BQ':'ffc600',
    'EH':'99334d',
    'FG':'99334d',
    'OU':'00ffff',
    'CE':'9900ff',
    'EQ':'99334d',
    'GJM':'805642',
    'EU':'99334d',
    'FJ':'99334d'
    }

In [48]:
gff_geo3918 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/gff_files/geo_3918.gff', sep='\t', header=None)
eggNOG_annot_geo3918 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/eggNOG_annot/geo3918_eggNOG.tsv', sep='\t')
gff_Jay535 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/gff_files/Jay_535.gff', sep='\t', header=None)
eggNOG_annot_Jay535 = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/eggNOG_annot/Jay_535_eggNOG.tsv', sep='\t', header = 4)

In [52]:
eggNOG_annot_Jay535['Unnamed: 6'] = eggNOG_annot_Jay535['Unnamed: 6'].apply(lambda x:x[0])

In [54]:
for idx, row in gff_geo3918.iterrows():
    for idx2, row2, in eggNOG_annot_geo3918.iterrows():
        if row2['ID'] in row[8]:
            gff_geo3918.loc[idx, 'color'] = d[row2['COG_category']]

for idx, row in gff_Jay535.iterrows():
    for idx2, row2, in eggNOG_annot_Jay535.iterrows():
        if row2['Unnamed: 0'] in row[8]:
            gff_Jay535.loc[idx, 'color'] = d[row2['Unnamed: 6']]

In [56]:
gff_geo3918_plus_strand = gff_geo3918[gff_geo3918[6] == '+']
gff_geo3918_minus_strand = gff_geo3918[gff_geo3918[6] == '-']
gff_Jay535_plus_strand = gff_Jay535[gff_Jay535[6] == '+']
gff_Jay535_minus_strand = gff_Jay535[gff_Jay535[6] == '-']

In [57]:
for idx, row in gff_geo3918_plus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/Jay_535_geo3918/data/highlight_plus_strand.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

for idx, row in gff_geo3918_minus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/Jay_535_geo3918/data/highlight_minus_strand.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

for idx, row in gff_Jay535_plus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/Jay_535_geo3918/data/highlight_plus_strand.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

for idx, row in gff_Jay535_minus_strand.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/Jay_535_geo3918/data/highlight_minus_strand.txt', 'a') as write_file:
        write_file.write(f"{row[0]} {row[3]} {row[4]} {row['color']}\n")

In [58]:
seed_compare = pd.read_csv('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/seq_data/SEED_compare/geo3918_Jay_535.tsv', sep='\t')

In [60]:
seed_compare_parsed = seed_compare[['Gene id', 'Gene id.1']]
seed_compare_parsed = seed_compare_parsed[seed_compare_parsed['Gene id.1'] != ' ']
gff_geo3918['color'] = gff_geo3918['color'].fillna('gray_a2')

In [61]:
for idx, row in seed_compare_parsed.iterrows():
    for idx2, row2 in gff_geo3918.iterrows():
        if row['Gene id'] in row2[8]:
            seed_compare_parsed.loc[idx,'start1'] = row2[3]
            seed_compare_parsed.loc[idx,'stop1'] = row2[4]
            seed_compare_parsed.loc[idx,'link_id_1'] = row2[0]
            seed_compare_parsed.loc[idx,'color'] = row2['color']

for idx, row in seed_compare_parsed.iterrows():
    for idx2, row2 in gff_Jay535.iterrows():
        if row['Gene id.1'] in row2[8]:
            seed_compare_parsed.loc[idx,'start2'] = row2[3]
            seed_compare_parsed.loc[idx,'stop2'] = row2[4]
            seed_compare_parsed.loc[idx,'link_id_2'] = row2[0]

In [ ]:
for idx, row in seed_compare_parsed.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/geo3918_geo3817/data/links.txt', 'a') as link_file:
        link_file.write(f"rep{idx} {row['link_id_1']} {int(row['start1'])} {int(row['stop1'])}\nrep{idx} {row['link_id_2']} {int(row['start2'])} {int(row['stop2'])}\n")

In [62]:
for idx, row in seed_compare_parsed.iterrows():
    with open('/home/aster/Project_Geoarchaeota_28.11/results/novel_circos_diag/Jay_535_geo3918/data/links.txt', 'a') as link_file:
        link_file.write(f"{row['link_id_1']} {int(row['start1'])} {int(row['stop1'])} {row['link_id_2']} {int(row['start2'])} {int(row['stop2'])} color={row['color']}\n")